### ISSUE TITLE
Oppertunity on refactoring

### ISSUE THREAD

**Issue by Bellfalasch** [Yan-MX/departureboard#3]
Hi @Yan-MX ,

Some suggestions, could some of them be resolved? Tag me in the PR and I will have an updated look at it. You don't have to do these, but it is appreciated if you do. It will also be weighted against project total.

* `iframe` is usually unwanted solution to problems, can you achieve as similar visuals in another way?
* Can the overall CSS quality be updated (inline styling, stylesheet dead code, etc)?
* Can all attributes for styling be replaced with CSS equivalents?
* Some improvement to code repetition?
* Some attributes used on `img` doesn't exists in the W3C spec, can this be fixed?

More ideas are appreciated but not needed.

**Comment by Yan-MX** [comment]
thanks for feedback! Definitely, will work on it and tag you later.

**Comment by Yan-MX** [comment]
@Bellfalasch I did refactoring based on your feedback :) please take a look.

**Comment by Bellfalasch** [comment]
Fantastic! Looks very good.
